services:
  app:
    build: .
    container_name: ciwork_app
    env_file: .env.production
    ports:
      - '127.0.0.1:3000:3000'
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - ciwork_net

  mongo:
    image: mongo:6.0
    container_name: mongo_db
    command:
      ['mongod', '--setParameter', 'diagnosticDataCollectionEnabled=false']
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret123
    volumes:
      - ciwork_ciwork_db_data:/data/db
    restart: unless-stopped
    networks:
      - ciwork_net

  caddy:
    image: caddy:2
    container_name: ciwork_caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - ciwork_net


volumes:
  ciwork_ciwork_db_data:
    external: true
  caddy_data:
  caddy_config:


networks:
  ciwork_net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: '1450'

